#pragma once

#include <Arduino.h>

constexpr uint8_t DIGITS[] = {DIG_0, DIG_1, DIG_2, DIG_3, DIG_4, DIG_5, DIG_6, DIG_7, DIG_8, DIG_9};

constexpr uint32_t SEGMENT_A_MASK  = 1UL << SEG_A;
constexpr uint32_t SEGMENT_B_MASK  = 1UL << SEG_B;
constexpr uint32_t SEGMENT_C_MASK  = 1UL << SEG_C;
constexpr uint32_t SEGMENT_D_MASK  = 1UL << SEG_D;
constexpr uint32_t SEGMENT_E_MASK  = 1UL << SEG_E;
constexpr uint32_t SEGMENT_F_MASK  = 1UL << SEG_F;
constexpr uint32_t SEGMENT_G_MASK  = 1UL << SEG_G;
constexpr uint32_t SEGMENT_UL_MASK = 1UL << SEG_UL;
constexpr uint32_t SEGMENT_DP_MASK = 1UL << SEG_DP;
constexpr uint32_t SEGMENT_CO_MASK = 1UL << SEG_CO;
constexpr uint32_t SEGMENT_MASKS[] = {SEGMENT_A_MASK, SEGMENT_B_MASK, SEGMENT_C_MASK, SEGMENT_D_MASK, SEGMENT_E_MASK, SEGMENT_F_MASK, SEGMENT_G_MASK, SEGMENT_UL_MASK, SEGMENT_DP_MASK, SEGMENT_CO_MASK};
constexpr uint32_t SEGMENT_SPINNER_MASKS[] = {SEGMENT_A_MASK, SEGMENT_B_MASK, SEGMENT_C_MASK, SEGMENT_D_MASK, SEGMENT_E_MASK, SEGMENT_F_MASK};
/* We can only assume the segments' order until we actually test the board.
*   _
* |   |
*   _
* |   |
*   _
*    .
*     ,
*   A
* F   B
*   G
* E   C
*   D
*    DP
*     H
*/

// OR all of the mask bits in
constexpr uint32_t PATTERN_CLEAR  = 0;
constexpr uint32_t PATTERN_FULL   = SEGMENT_A_MASK | SEGMENT_B_MASK | SEGMENT_C_MASK | SEGMENT_D_MASK | SEGMENT_E_MASK | SEGMENT_F_MASK | SEGMENT_G_MASK | SEGMENT_UL_MASK | SEGMENT_DP_MASK | SEGMENT_CO_MASK;
constexpr uint32_t PATTERN_0      = SEGMENT_A_MASK | SEGMENT_B_MASK | SEGMENT_C_MASK | SEGMENT_D_MASK | SEGMENT_E_MASK | SEGMENT_F_MASK;
constexpr uint32_t PATTERN_1      = SEGMENT_B_MASK | SEGMENT_C_MASK;
constexpr uint32_t PATTERN_2      = SEGMENT_A_MASK | SEGMENT_B_MASK | SEGMENT_G_MASK | SEGMENT_E_MASK | SEGMENT_D_MASK;
constexpr uint32_t PATTERN_3      = SEGMENT_A_MASK | SEGMENT_B_MASK | SEGMENT_G_MASK | SEGMENT_C_MASK | SEGMENT_D_MASK;
constexpr uint32_t PATTERN_4      = SEGMENT_F_MASK | SEGMENT_G_MASK | SEGMENT_C_MASK | SEGMENT_B_MASK;
constexpr uint32_t PATTERN_5      = SEGMENT_A_MASK | SEGMENT_F_MASK | SEGMENT_G_MASK | SEGMENT_C_MASK | SEGMENT_D_MASK;
constexpr uint32_t PATTERN_6      = SEGMENT_F_MASK | SEGMENT_E_MASK | SEGMENT_D_MASK | SEGMENT_C_MASK | SEGMENT_G_MASK;
constexpr uint32_t PATTERN_7      = SEGMENT_A_MASK | SEGMENT_B_MASK | SEGMENT_C_MASK;
constexpr uint32_t PATTERN_8      = SEGMENT_A_MASK | SEGMENT_B_MASK | SEGMENT_C_MASK | SEGMENT_D_MASK | SEGMENT_E_MASK | SEGMENT_F_MASK | SEGMENT_G_MASK;
constexpr uint32_t PATTERN_9      = SEGMENT_G_MASK | SEGMENT_F_MASK | SEGMENT_A_MASK | SEGMENT_B_MASK | SEGMENT_C_MASK;
constexpr uint32_t PATTERN_DP     = SEGMENT_DP_MASK;
constexpr uint32_t PATTERN_UNDERLINE = SEGMENT_UL_MASK;
constexpr uint32_t PATTERN_COMMA     = SEGMENT_CO_MASK;

constexpr uint32_t PATTERN_NUMBERS[] = {PATTERN_0, PATTERN_1, PATTERN_2, PATTERN_3, PATTERN_4, PATTERN_5, PATTERN_6, PATTERN_7, PATTERN_8, PATTERN_9};
